# frozen_string_literal: true

# Code generated by SdkContractGenerator. DO NOT EDIT.

module RunApi
  module GptImage2
    CONTRACT = {
      "edit-image" => {
        "models" => ["gpt-image-2"],
        "fields_by_model" => {
          "gpt-image-2" => {
            "aspect_ratio" => {
              "enum" => ["auto", "1:1", "3:2", "2:3", "4:3", "3:4", "5:4", "4:5", "16:9", "9:16", "2:1", "1:2", "3:1", "1:3", "21:9", "9:21"]
            },
            "output_resolution" => {
              "enum" => ["1k", "2k", "4k"]
            },
            "prompt" => {
              "required" => true
            },
            "source_image_urls" => {
              "required" => true
            }
          }
        }
      },
      "text-to-image" => {
        "models" => ["gpt-image-2"],
        "fields_by_model" => {
          "gpt-image-2" => {
            "aspect_ratio" => {
              "enum" => ["auto", "1:1", "3:2", "2:3", "4:3", "3:4", "5:4", "4:5", "16:9", "9:16", "2:1", "1:2", "3:1", "1:3", "21:9", "9:21"]
            },
            "output_resolution" => {
              "enum" => ["1k", "2k", "4k"]
            },
            "prompt" => {
              "required" => true
            }
          }
        }
      }
    }.freeze
  end
end
